name: "flutter_template_app"
version: 0.1.0
publish_to: none
environment:
  sdk: "3.5.4"
description: A new Flutter project.
dependencies:
  dio: 5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  fluttertoast: 8.2.8
  freezed: 2.5.7
  freezed_annotation: 2.4.4
  go_router: 14.6.1
  hooks_riverpod: 2.6.1
  json_annotation: 4.9.0
  material_symbols_icons: 4.2800.0
  retrofit: 4.4.1
  riverpod_annotation: 2.6.1
  shared_preferences: 2.3.3
dev_dependencies:
  build_runner: 2.4.13
  flutter_lints: "5.0.0"
  flutter_test:
    sdk: flutter
  json_serializable: 6.9.0
  mockito: 5.4.4
  pedantic_mono: "1.29.0"
  pubspec_dependency_sorter: "1.0.5"
  retrofit_generator: 9.1.5
  riverpod_generator: 2.6.3
  test: 1.25.9
flutter:
  uses-material-design: true
