name: "flutter_template_app"
version: 0.1.0
publish_to: none
environment:
  sdk: "3.6.1"
description: A new Flutter project.
dependencies:
  dio: 5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  fluttertoast: 8.2.10
  freezed: 2.5.8
  freezed_annotation: 2.4.4
  go_router: 14.7.1
  hooks_riverpod: 2.6.1
  json_annotation: 4.9.0
  material_symbols_icons: 4.2801.1
  retrofit: 4.4.2
  riverpod_annotation: 2.6.1
  shared_preferences: 2.4.0
dev_dependencies:
  build_runner: 2.4.14
  flutter_lints: "5.0.0"
  flutter_test:
    sdk: flutter
  json_serializable: 6.9.3
  mockito: 5.4.5
  pedantic_mono: "1.29.0"
  pubspec_dependency_sorter: "1.0.5"
  retrofit_generator: 9.1.7
  riverpod_generator: 2.6.4
flutter:
  uses-material-design: true
