name: "flutter_template_app"
version: 0.1.0
publish_to: none
environment:
  sdk: "3.7.2"
description: A new Flutter project.
dependencies:
  dio: 5.8.0+1
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.2
  fluttertoast: 8.2.12
  freezed: 2.5.8
  freezed_annotation: 2.4.4
  go_router: 14.8.1
  hooks_riverpod: 2.6.1
  json_annotation: 4.9.0
  material_symbols_icons: 4.2810.1
  retrofit: 4.4.2
  riverpod_annotation: 2.6.1
  shared_preferences: 2.5.2
dev_dependencies:
  build_runner: 2.4.15
  flutter_lints: "5.0.0"
  flutter_test:
    sdk: flutter
  json_serializable: 6.9.4
  mockito: 5.4.5
  pedantic_mono: "1.30.3"
  pubspec_dependency_sorter: "1.0.5"
  retrofit_generator: 9.1.9
  riverpod_generator: 2.6.4
flutter:
  uses-material-design: true
