name: "flutter_template_app"
version: 0.1.0
publish_to: none
environment:
  sdk: "^3.5.4"
description: A new Flutter project.
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: "^4.0.0"
  flutter_test:
    sdk: flutter
  pedantic_mono: "^1.28.0"
  pubspec_dependency_sorter: "^1.0.5"
flutter:
  uses-material-design: true
