name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: 3.7.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: 3.10.2
  widgetbook_annotation: 3.2.0
  flutter_template_app:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  widgetbook_generator: 3.9.1
  build_runner: 2.4.14

dependency_overrides:
  source_gen: ^1.1.0
  dart_style: ^2.3.0
  analyzer: ^6.0.0
  freezed: 2.5.7
flutter:
  uses-material-design: true
